name: Test Action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
    build:
      runs-on: ubuntu-latest
    
    steps:
      - name: Test output
          run: echo "Hello world!"
